// GENERATED by build_tiles.py -- do not edit by hand.
// Families present in the exported tiles, with the classes
// inside each and their cluster counts.
//
// The family is the unit the exporter thins by, which is
// what makes hiding a family backfill instead of leaving
// holes. Narrowing to individual classes is finer than that
// and has to re-thin on the device; see thinning.ts.
export type FilterClass = {
  /** The register's own Swedish class name, used as label. */
  id: string;
  /** counts[i] survives `stars >= i + 1`; [0] is the total. */
  counts: number[];
};

export type FilterFamily = {
  /** Resolve to a display name in the frontend, not here. */
  id: string;
  /** Glyph name; served as /fornlamningar-icons/svg/<icon>.svg */
  icon: string;
  /** counts[i] survives `stars >= i + 1`; [0] is the total. */
  counts: number[];
  /** Present in the export, best represented first. */
  classes: FilterClass[];
};

export const FILTER_FAMILIES: FilterFamily[] = [
  {
    id: "graves",
    icon: "burial-mound",
    counts: [5818, 4815, 3216, 1430, 384],
    classes: [
      { id: "Gravfält", counts: [1923, 1561, 975, 375, 84] },
      { id: "Hög", counts: [1515, 1273, 891, 442, 128] },
      { id: "Stenkammargrav", counts: [560, 490, 342, 165, 44] },
      { id: "Stensättning", counts: [389, 287, 169, 54, 12] },
      { id: "Röse", counts: [324, 254, 167, 43, 13] },
      { id: "Grav markerad av sten/block", counts: [304, 254, 165, 86, 17] },
      { id: "Begravningsplats", counts: [298, 270, 210, 116, 38] },
      { id: "Stenkrets/stenrad", counts: [210, 167, 100, 37, 13] },
      { id: "Minnesmärke", counts: [182, 169, 139, 81, 28] },
      { id: "Grav- och boplatsområde", counts: [69, 56, 36, 18, 3] },
      { id: "Labyrint", counts: [18, 13, 9, 8, 2] },
      { id: "Gravklot", counts: [5, 5, 2, 0, 0] },
      { id: "Gravvård", counts: [5, 3, 1, 1, 1] },
      { id: "Stenkistgrav", counts: [4, 2, 1, 1, 1] },
      { id: "Grav - uppgift om typ saknas", counts: [3, 3, 2, 1, 0] },
      { id: "Gravhägnad", counts: [3, 3, 2, 1, 0] },
      { id: "Begravningsplats enstaka", counts: [2, 1, 1, 1, 0] },
      { id: "Flatmarksgrav", counts: [2, 2, 2, 0, 0] },
      { id: "Grav övrig", counts: [2, 2, 2, 0, 0] },
    ],
  },
  {
    id: "rockart",
    icon: "runestone",
    counts: [1691, 1481, 1100, 613, 213],
    classes: [
      { id: "Runristning", counts: [993, 919, 750, 477, 183] },
      { id: "Hällristning", counts: [626, 502, 304, 115, 19] },
      { id: "Hällmålning", counts: [31, 25, 20, 8, 2] },
      { id: "Ristning, medeltid/historisk tid", counts: [22, 17, 12, 4, 3] },
      { id: "Bildristning", counts: [19, 18, 14, 9, 6] },
    ],
  },
  {
    id: "forts",
    icon: "castle",
    counts: [1112, 1023, 827, 523, 237],
    classes: [
      { id: "Fornborg", counts: [619, 548, 414, 223, 72] },
      { id: "Borg", counts: [204, 200, 176, 133, 79] },
      { id: "Fästning/skans", counts: [181, 169, 146, 92, 36] },
      { id: "Slott/herresäte", counts: [54, 54, 48, 38, 25] },
      { id: "Stadsbefästning", counts: [18, 18, 18, 18, 15] },
      { id: "Stadsvall/stadsmur", counts: [14, 14, 13, 13, 7] },
      { id: "Spärranordning", counts: [6, 5, 4, 3, 2] },
      { id: "Stridsvärn", counts: [6, 6, 1, 0, 0] },
      { id: "Område med militära anläggningar", counts: [4, 3, 1, 1, 0] },
      { id: "Militär anläggning övrig", counts: [3, 3, 3, 2, 1] },
      { id: "Vallanläggning", counts: [3, 3, 3, 0, 0] },
    ],
  },
  {
    id: "religious",
    icon: "church",
    counts: [387, 348, 287, 196, 109],
    classes: [
      { id: "Kyrka/kapell", counts: [250, 234, 203, 145, 79] },
      { id: "Källa med tradition", counts: [55, 43, 27, 11, 1] },
      { id: "Kloster", counts: [30, 30, 30, 30, 24] },
      { id: "Naturföremål/-bildning med bruk, tradition eller namn", counts: [26, 19, 14, 6, 2] },
      { id: "Avrättningsplats", counts: [11, 10, 5, 2, 2] },
      { id: "Samlingsplats", counts: [8, 6, 4, 2, 1] },
      { id: "Plats med tradition", counts: [5, 4, 3, 0, 0] },
      { id: "Offerkast", counts: [2, 2, 1, 0, 0] },
    ],
  },
  {
    id: "settlement",
    icon: "settlement",
    counts: [237, 204, 134, 65, 18],
    classes: [
      { id: "Stadslager", counts: [107, 100, 72, 38, 11] },
      { id: "Hägnad", counts: [27, 20, 12, 4, 1] },
      { id: "Husgrund, förhistorisk/medeltida", counts: [21, 18, 15, 7, 1] },
      { id: "Bytomt/gårdstomt", counts: [19, 18, 9, 6, 2] },
      { id: "Boplats", counts: [16, 11, 4, 1, 0] },
      { id: "Boplatsområde", counts: [10, 9, 4, 1, 0] },
      { id: "Husgrund, historisk tid", counts: [10, 9, 6, 4, 1] },
      { id: "Park-/trädgårdsanläggning", counts: [10, 8, 7, 2, 1] },
      { id: "Hägnadssystem", counts: [8, 6, 3, 1, 1] },
      { id: "Lägenhetsbebyggelse", counts: [5, 3, 1, 0, 0] },
      { id: "Kyrkstad", counts: [2, 1, 0, 0, 0] },
      { id: "Boplatslämning övrig", counts: [1, 0, 0, 0, 0] },
      { id: "Boplatsvall", counts: [1, 1, 1, 1, 0] },
    ],
  },
  {
    id: "farming",
    icon: "fossil-field",
    counts: [18, 13, 6, 3, 1],
    classes: [
      { id: "Dike/ränna", counts: [7, 6, 4, 2, 1] },
      { id: "Dammvall", counts: [5, 3, 2, 1, 0] },
      { id: "Terrassering", counts: [4, 4, 0, 0, 0] },
      { id: "Fossil åker", counts: [1, 0, 0, 0, 0] },
      { id: "Stenröjd yta", counts: [1, 0, 0, 0, 0] },
    ],
  },
  {
    id: "industry",
    icon: "furnace",
    counts: [478, 399, 277, 101, 21],
    classes: [
      { id: "Hyttområde", counts: [148, 117, 74, 18, 2] },
      { id: "Hammarområde", counts: [87, 78, 54, 27, 7] },
      { id: "Hytt- och hammarområde", counts: [60, 55, 47, 26, 6] },
      { id: "Hyttlämning", counts: [40, 35, 24, 9, 0] },
      { id: "Metallindustri/järnbruk", counts: [27, 24, 18, 7, 3] },
      { id: "Gruvområde", counts: [20, 14, 13, 3, 1] },
      { id: "Hammare/smedja", counts: [20, 16, 12, 2, 0] },
      { id: "Industri övrig", counts: [10, 8, 5, 0, 0] },
      { id: "Kvarn", counts: [9, 7, 3, 1, 0] },
      { id: "Småindustriområde", counts: [9, 7, 3, 2, 0] },
      { id: "Glasindustri", counts: [7, 5, 4, 2, 1] },
      { id: "Kalkugn", counts: [7, 6, 5, 1, 0] },
      { id: "Gruvhål", counts: [6, 4, 3, 0, 0] },
      { id: "Pappersindustri", counts: [6, 5, 5, 3, 1] },
      { id: "Tegelindustri", counts: [5, 2, 1, 0, 0] },
      { id: "Träindustri", counts: [4, 3, 1, 0, 0] },
      { id: "Uppfordringsanläggning", counts: [3, 3, 1, 0, 0] },
      { id: "Bergshistorisk lämning övrig", counts: [2, 2, 0, 0, 0] },
      { id: "Livsmedelsindustri", counts: [2, 2, 1, 0, 0] },
      { id: "Smideslämning", counts: [2, 2, 0, 0, 0] },
      { id: "Blästbrukslämning", counts: [1, 1, 0, 0, 0] },
      { id: "Brott/täkt", counts: [1, 1, 1, 0, 0] },
      { id: "Gjuteri", counts: [1, 1, 1, 0, 0] },
      { id: "Område med flottningsanläggningar", counts: [1, 1, 1, 0, 0] },
    ],
  },
  {
    id: "transport",
    icon: "bridge",
    counts: [176, 149, 109, 54, 16],
    classes: [
      { id: "Bro", counts: [92, 75, 54, 25, 6] },
      { id: "Färdväg", counts: [26, 21, 15, 7, 4] },
      { id: "Gränsbestämt område", counts: [23, 23, 20, 13, 5] },
      { id: "Kanal", counts: [13, 13, 10, 5, 0] },
      { id: "Färdvägssystem", counts: [9, 5, 3, 1, 0] },
      { id: "Vägmärke", counts: [8, 8, 5, 2, 1] },
      { id: "Gränsmärke", counts: [4, 3, 2, 1, 0] },
      { id: "Vad", counts: [1, 1, 0, 0, 0] },
    ],
  },
  {
    id: "maritime",
    icon: "lighthouse",
    counts: [53, 44, 27, 8, 1],
    classes: [
      { id: "Hamnanläggning", counts: [16, 13, 7, 2, 0] },
      { id: "Fartygs-/båtlämning", counts: [12, 10, 7, 4, 0] },
      { id: "Fiskeläge", counts: [10, 8, 2, 0, 0] },
      { id: "Fyr", counts: [4, 4, 4, 1, 1] },
      { id: "Hamnområde", counts: [4, 3, 3, 0, 0] },
      { id: "Varv/slip", counts: [3, 3, 3, 1, 0] },
      { id: "Ballastplats", counts: [1, 1, 0, 0, 0] },
      { id: "Båtlänning", counts: [1, 1, 0, 0, 0] },
      { id: "Sjömärke", counts: [1, 0, 0, 0, 0] },
      { id: "Vårdkase", counts: [1, 1, 1, 0, 0] },
    ],
  },
  {
    id: "hunting",
    icon: "pitfall-trap",
    counts: [19, 16, 10, 2, 0],
    classes: [
      { id: "Fångstgrop", counts: [9, 6, 5, 0, 0] },
      { id: "Fångstanläggning övrig", counts: [5, 5, 3, 1, 0] },
      { id: "Fångstgropssystem", counts: [4, 4, 2, 1, 0] },
      { id: "Fångstgård", counts: [1, 1, 0, 0, 0] },
    ],
  },
  {
    id: "misc",
    icon: "unknown",
    counts: [11, 9, 8, 6, 1],
    classes: [
      { id: "Övrigt", counts: [7, 6, 5, 5, 1] },
      { id: "Fornlämningsliknande bildning", counts: [3, 3, 3, 1, 0] },
      { id: "Fyndplats", counts: [1, 0, 0, 0, 0] },
    ],
  },
];

export const ALL_FAMILY_IDS = FILTER_FAMILIES.map(f => f.id);
