// GENERATED by build_tiles.py -- do not edit by hand.
// Families present in the exported tiles, with the classes
// inside each and their cluster counts.
//
// The family is the unit the exporter thins by, which is
// what makes hiding a family backfill instead of leaving
// holes. Narrowing to individual classes is finer than that
// and has to re-thin on the device; see thinning.ts.
export type FilterClass = {
  /** The register's own Swedish class name, used as label. */
  id: string;
  /** counts[i] survives `stars >= i + 1`; [0] is the total. */
  counts: number[];
};

export type FilterFamily = {
  /** Resolve to a display name in the frontend, not here. */
  id: string;
  /** Glyph name; served as /fornlamningar-icons/svg/<icon>.svg */
  icon: string;
  /** counts[i] survives `stars >= i + 1`; [0] is the total. */
  counts: number[];
  /** Present in the export, best represented first. */
  classes: FilterClass[];
};

export const FILTER_FAMILIES: FilterFamily[] = [
  {
    id: "graves",
    icon: "burial-mound",
    counts: [51594, 51256, 46422, 26529, 7841],
    classes: [
      { id: "Gravfält", counts: [16603, 16603, 16433, 11083, 2892] },
      { id: "Röse", counts: [12092, 12087, 8509, 1775, 395] },
      { id: "Hög", counts: [9371, 9371, 9360, 6472, 1944] },
      { id: "Stensättning", counts: [5378, 5346, 4728, 2127, 518] },
      { id: "Grav markerad av sten/block", counts: [2047, 2047, 1961, 1226, 390] },
      { id: "Stenkammargrav", counts: [1787, 1787, 1786, 1459, 611] },
      { id: "Stenkrets/stenrad", counts: [1308, 1308, 1267, 874, 297] },
      { id: "Grav- och boplatsområde", counts: [1107, 1107, 1051, 495, 110] },
      { id: "Begravningsplats", counts: [604, 604, 604, 580, 415] },
      { id: "Begravningsplats enstaka", counts: [368, 94, 14, 4, 2] },
      { id: "Minnesmärke", counts: [297, 297, 297, 287, 223] },
      { id: "Labyrint", counts: [183, 183, 134, 57, 21] },
      { id: "Flatmarksgrav", counts: [114, 114, 104, 27, 4] },
      { id: "Skärvstenshög", counts: [105, 99, 46, 5, 0] },
      { id: "Grav - uppgift om typ saknas", counts: [64, 53, 28, 3, 2] },
      { id: "Grav övrig", counts: [47, 45, 22, 7, 2] },
      { id: "Gravhägnad", counts: [33, 33, 15, 3, 3] },
      { id: "Stenkistgrav", counts: [26, 26, 26, 18, 4] },
      { id: "Stenring", counts: [23, 15, 1, 0, 0] },
      { id: "Gravklot", counts: [22, 22, 22, 20, 5] },
      { id: "Gravvård", counts: [13, 13, 12, 7, 3] },
      { id: "Järnåldersdös", counts: [2, 2, 2, 0, 0] },
    ],
  },
  {
    id: "rockart",
    icon: "runestone",
    counts: [16258, 16249, 14618, 5418, 1869],
    classes: [
      { id: "Hällristning", counts: [14157, 14156, 12742, 3813, 583] },
      { id: "Runristning", counts: [1392, 1392, 1392, 1385, 1219] },
      { id: "Ristning, medeltid/historisk tid", counts: [538, 536, 351, 133, 28] },
      { id: "Hällmålning", counts: [61, 61, 60, 39, 15] },
      { id: "Kompassros/väderstreckspil", counts: [57, 51, 20, 2, 0] },
      { id: "Bildristning", counts: [53, 53, 53, 46, 24] },
    ],
  },
  {
    id: "forts",
    icon: "castle",
    counts: [2046, 2044, 1994, 1848, 1351],
    classes: [
      { id: "Fornborg", counts: [1181, 1181, 1181, 1145, 782] },
      { id: "Fästning/skans", counts: [281, 281, 281, 273, 218] },
      { id: "Borg", counts: [260, 260, 260, 255, 225] },
      { id: "Stridsvärn", counts: [77, 77, 58, 25, 12] },
      { id: "Vallanläggning", counts: [75, 75, 68, 28, 12] },
      { id: "Slott/herresäte", counts: [61, 61, 61, 61, 57] },
      { id: "Spärranordning", counts: [41, 39, 19, 6, 3] },
      { id: "Område med militära anläggningar", counts: [19, 19, 18, 13, 5] },
      { id: "Stadsbefästning", counts: [18, 18, 18, 18, 18] },
      { id: "Stadsvall/stadsmur", counts: [14, 14, 14, 14, 14] },
      { id: "Militär anläggning övrig", counts: [11, 11, 9, 6, 4] },
      { id: "Militär mötesplats", counts: [5, 5, 5, 4, 1] },
      { id: "Slagfält", counts: [2, 2, 2, 0, 0] },
      { id: "Luftfarkost", counts: [1, 1, 0, 0, 0] },
    ],
  },
  {
    id: "religious",
    icon: "church",
    counts: [2219, 1982, 1483, 895, 443],
    classes: [
      { id: "Källa med tradition", counts: [663, 663, 586, 325, 70] },
      { id: "Naturföremål/-bildning med bruk, tradition eller namn", counts: [524, 497, 306, 138, 44] },
      { id: "Kyrka/kapell", counts: [320, 320, 320, 315, 273] },
      { id: "Offerkast", counts: [303, 207, 80, 11, 2] },
      { id: "Offerplats", counts: [164, 57, 11, 1, 0] },
      { id: "Plats med tradition", counts: [68, 65, 41, 14, 5] },
      { id: "Avrättningsplats", counts: [66, 66, 62, 35, 9] },
      { id: "Brunn/kallkälla", counts: [51, 47, 17, 4, 0] },
      { id: "Kloster", counts: [32, 32, 32, 32, 32] },
      { id: "Samlingsplats", counts: [28, 28, 28, 20, 8] },
    ],
  },
  {
    id: "settlement",
    icon: "settlement",
    counts: [26324, 19144, 5599, 941, 247],
    classes: [
      { id: "Bytomt/gårdstomt", counts: [5250, 4217, 1136, 98, 25] },
      { id: "Lägenhetsbebyggelse", counts: [5132, 3844, 911, 41, 7] },
      { id: "Hägnad", counts: [4061, 3020, 566, 166, 35] },
      { id: "Boplatsområde", counts: [2512, 2178, 839, 79, 11] },
      { id: "Husgrund, förhistorisk/medeltida", counts: [1653, 1641, 604, 134, 35] },
      { id: "Boplats", counts: [1516, 1481, 830, 176, 18] },
      { id: "Hägnadssystem", counts: [1404, 720, 145, 48, 11] },
      { id: "Fäbod", counts: [1292, 922, 160, 6, 0] },
      { id: "Tomtning", counts: [1056, 162, 23, 2, 0] },
      { id: "Husgrund, historisk tid", counts: [773, 471, 128, 27, 7] },
      { id: "Kåta", counts: [682, 37, 1, 0, 0] },
      { id: "Viste", counts: [356, 44, 3, 0, 0] },
      { id: "Bengömma", counts: [153, 20, 1, 0, 0] },
      { id: "Stadslager", counts: [126, 126, 126, 126, 89] },
      { id: "Härd", counts: [95, 71, 26, 4, 0] },
      { id: "Stalotomt", counts: [73, 20, 2, 0, 0] },
      { id: "Boplatslämning övrig", counts: [41, 41, 37, 12, 0] },
      { id: "Boplatsgrop", counts: [28, 26, 14, 4, 0] },
      { id: "Renvall", counts: [26, 16, 2, 0, 0] },
      { id: "Gistgård", counts: [22, 18, 5, 2, 1] },
      { id: "Skåre/jaktvärn", counts: [16, 15, 4, 0, 0] },
      { id: "Park-/trädgårdsanläggning", counts: [13, 13, 13, 10, 6] },
      { id: "Boplatsvall", counts: [12, 12, 11, 2, 1] },
      { id: "Kokgrop", counts: [11, 9, 2, 0, 0] },
      { id: "Förvaringsanläggning", counts: [8, 8, 2, 0, 0] },
      { id: "Rengärda", counts: [7, 6, 2, 0, 0] },
      { id: "Kyrkstad", counts: [6, 6, 6, 4, 1] },
    ],
  },
  {
    id: "farming",
    icon: "fossil-field",
    counts: [1565, 1251, 484, 116, 18],
    classes: [
      { id: "Dammvall", counts: [567, 343, 122, 36, 3] },
      { id: "Område med fossil åkermark", counts: [308, 301, 133, 23, 1] },
      { id: "Fossil åker", counts: [249, 237, 94, 17, 0] },
      { id: "Terrassering", counts: [187, 140, 39, 16, 4] },
      { id: "Röjningsröse", counts: [116, 94, 12, 1, 0] },
      { id: "Dike/ränna", counts: [75, 74, 55, 17, 10] },
      { id: "Stenröjd yta", counts: [35, 34, 20, 4, 0] },
      { id: "Område med skogsbrukslämningar", counts: [28, 28, 9, 2, 0] },
    ],
  },
  {
    id: "industry",
    icon: "furnace",
    counts: [10589, 6085, 3272, 1649, 699],
    classes: [
      { id: "Blästbrukslämning", counts: [3333, 641, 28, 6, 2] },
      { id: "Blästplats", counts: [1438, 275, 18, 1, 0] },
      { id: "Hyttområde", counts: [825, 823, 700, 439, 207] },
      { id: "Kvarn", counts: [798, 511, 162, 22, 3] },
      { id: "Gruvområde", counts: [741, 735, 535, 251, 61] },
      { id: "Kalkugn", counts: [682, 565, 216, 59, 13] },
      { id: "Småindustriområde", counts: [303, 237, 90, 26, 8] },
      { id: "Hyttlämning", counts: [296, 296, 293, 222, 102] },
      { id: "Hammarområde", counts: [289, 289, 272, 203, 92] },
      { id: "Gruvhål", counts: [234, 187, 63, 20, 3] },
      { id: "Brott/täkt", counts: [218, 192, 81, 14, 3] },
      { id: "Träindustri", counts: [162, 161, 131, 53, 20] },
      { id: "Stenugn", counts: [147, 79, 11, 3, 0] },
      { id: "Kolningsanläggning", counts: [136, 130, 50, 8, 0] },
      { id: "Livsmedelsindustri", counts: [113, 110, 51, 20, 8] },
      { id: "Tegelindustri", counts: [98, 91, 51, 18, 7] },
      { id: "Hammare/smedja", counts: [97, 97, 94, 50, 33] },
      { id: "Hytt- och hammarområde", counts: [93, 93, 93, 87, 64] },
      { id: "Uppfordringsanläggning", counts: [82, 80, 37, 14, 3] },
      { id: "Textilindustri", counts: [81, 81, 73, 23, 6] },
      { id: "Smideslämning", counts: [66, 62, 20, 3, 0] },
      { id: "Kemisk industri", counts: [58, 57, 20, 1, 0] },
      { id: "Flottningsanläggning", counts: [57, 56, 20, 2, 0] },
      { id: "Brytningsyta", counts: [56, 52, 10, 0, 0] },
      { id: "Metallindustri/järnbruk", counts: [48, 48, 47, 44, 32] },
      { id: "Glasindustri", counts: [35, 35, 35, 24, 13] },
      { id: "Bergshistorisk lämning övrig", counts: [32, 31, 12, 5, 1] },
      { id: "Industri övrig", counts: [29, 29, 25, 13, 8] },
      { id: "Pappersindustri", counts: [12, 12, 12, 11, 8] },
      { id: "Stenindustri", counts: [11, 11, 8, 1, 0] },
      { id: "Smidesområde", counts: [10, 10, 5, 2, 0] },
      { id: "Område med flottningsanläggningar", counts: [4, 4, 4, 2, 1] },
      { id: "Flintgruva", counts: [3, 3, 3, 0, 0] },
      { id: "Gjuteri", counts: [2, 2, 2, 2, 1] },
    ],
  },
  {
    id: "transport",
    icon: "bridge",
    counts: [14783, 8493, 1778, 625, 221],
    classes: [
      { id: "Vägmärke", counts: [9516, 5094, 232, 23, 8] },
      { id: "Färdväg", counts: [2564, 1426, 245, 90, 33] },
      { id: "Gränsmärke", counts: [1084, 441, 104, 18, 3] },
      { id: "Bro", counts: [755, 750, 597, 323, 133] },
      { id: "Färdvägssystem", counts: [623, 621, 470, 92, 13] },
      { id: "Rösning", counts: [99, 20, 0, 0, 0] },
      { id: "Gränsbestämt område", counts: [86, 86, 84, 49, 20] },
      { id: "Kanal", counts: [45, 44, 40, 27, 11] },
      { id: "Vad", counts: [11, 11, 6, 3, 0] },
    ],
  },
  {
    id: "maritime",
    icon: "lighthouse",
    counts: [1501, 1225, 487, 165, 53],
    classes: [
      { id: "Fartygs-/båtlämning", counts: [599, 448, 145, 35, 8] },
      { id: "Fiskeläge", counts: [473, 411, 134, 47, 15] },
      { id: "Hamnanläggning", counts: [103, 99, 73, 27, 11] },
      { id: "Kanalmärke", counts: [94, 94, 37, 5, 0] },
      { id: "Båtlänning", counts: [71, 58, 20, 2, 1] },
      { id: "Sjömärke", counts: [62, 20, 8, 6, 0] },
      { id: "Vårdkase", counts: [33, 29, 21, 9, 1] },
      { id: "Hamnområde", counts: [21, 21, 17, 12, 7] },
      { id: "Varv/slip", counts: [18, 18, 13, 9, 5] },
      { id: "Ballastplats", counts: [11, 11, 6, 4, 0] },
      { id: "Fyr", counts: [6, 6, 5, 5, 4] },
      { id: "Drag", counts: [5, 5, 4, 2, 1] },
      { id: "Område med fartygslämningar", counts: [4, 4, 3, 1, 0] },
      { id: "Förtöjningsanordning", counts: [1, 1, 1, 1, 0] },
    ],
  },
  {
    id: "hunting",
    icon: "pitfall-trap",
    counts: [598, 595, 369, 117, 31],
    classes: [
      { id: "Fångstgrop", counts: [441, 438, 249, 53, 8] },
      { id: "Fångstgropssystem", counts: [85, 85, 52, 17, 6] },
      { id: "Fångstanläggning övrig", counts: [65, 65, 61, 40, 15] },
      { id: "Fångstgård", counts: [7, 7, 7, 7, 2] },
    ],
  },
  {
    id: "misc",
    icon: "unknown",
    counts: [355, 340, 200, 53, 17],
    classes: [
      { id: "Övrigt", counts: [262, 257, 147, 31, 11] },
      { id: "Fyndplats", counts: [30, 30, 14, 1, 1] },
      { id: "Fornlämningsliknande bildning", counts: [25, 25, 25, 16, 4] },
      { id: "Fornlämningsliknande lämning", counts: [19, 19, 11, 5, 1] },
      { id: "Hornsamling", counts: [19, 9, 3, 0, 0] },
    ],
  },
];

export const ALL_FAMILY_IDS = FILTER_FAMILIES.map(f => f.id);
