// GENERATED by build_tiles.py -- do not edit by hand.
// Families present in the exported tiles, with the classes
// inside each and their cluster counts.
//
// The family is the unit the exporter thins by, which is
// what makes hiding a family backfill instead of leaving
// holes. Narrowing to individual classes is finer than that
// and has to re-thin on the device; see thinning.ts.
export type FilterClass = {
  /** The register's own Swedish class name, used as label. */
  id: string;
  /** counts[i] survives `stars >= i + 1`; [0] is the total. */
  counts: number[];
};

export type FilterFamily = {
  /** Resolve to a display name in the frontend, not here. */
  id: string;
  /** Glyph name; served as /fornlamningar-icons/svg/<icon>.svg */
  icon: string;
  /** counts[i] survives `stars >= i + 1`; [0] is the total. */
  counts: number[];
  /** Present in the export, best represented first. */
  classes: FilterClass[];
};

export const FILTER_FAMILIES: FilterFamily[] = [
  {
    id: "graves",
    icon: "burial-mound",
    counts: [6411, 5245, 3393, 1456, 345],
    classes: [
      { id: "Gravfält", counts: [1902, 1467, 851, 300, 51] },
      { id: "Hög", counts: [1814, 1493, 965, 429, 101] },
      { id: "Stenkammargrav", counts: [878, 761, 544, 259, 67] },
      { id: "Begravningsplats", counts: [431, 393, 315, 158, 45] },
      { id: "Stensättning", counts: [358, 289, 160, 56, 8] },
      { id: "Grav markerad av sten/block", counts: [335, 280, 164, 74, 17] },
      { id: "Röse", counts: [225, 169, 112, 39, 10] },
      { id: "Minnesmärke", counts: [213, 200, 166, 91, 33] },
      { id: "Stenkrets/stenrad", counts: [182, 135, 79, 35, 9] },
      { id: "Grav- och boplatsområde", counts: [31, 25, 17, 7, 1] },
      { id: "Stenkistgrav", counts: [15, 11, 4, 1, 1] },
      { id: "Skärvstenshög", counts: [8, 8, 6, 2, 0] },
      { id: "Labyrint", counts: [5, 3, 3, 2, 0] },
      { id: "Gravhägnad", counts: [3, 3, 2, 1, 0] },
      { id: "Gravvård", counts: [3, 3, 2, 1, 1] },
      { id: "Flatmarksgrav", counts: [2, 0, 0, 0, 0] },
      { id: "Grav - uppgift om typ saknas", counts: [2, 2, 2, 1, 1] },
      { id: "Gravklot", counts: [2, 1, 0, 0, 0] },
      { id: "Begravningsplats enstaka", counts: [1, 1, 1, 0, 0] },
      { id: "Grav övrig", counts: [1, 1, 0, 0, 0] },
    ],
  },
  {
    id: "rockart",
    icon: "runestone",
    counts: [1468, 1324, 1013, 510, 166],
    classes: [
      { id: "Runristning", counts: [1146, 1053, 837, 439, 145] },
      { id: "Hällristning", counts: [243, 202, 127, 50, 16] },
      { id: "Bildristning", counts: [30, 26, 24, 11, 2] },
      { id: "Hällmålning", counts: [26, 23, 10, 5, 2] },
      { id: "Ristning, medeltid/historisk tid", counts: [23, 20, 15, 5, 1] },
    ],
  },
  {
    id: "forts",
    icon: "castle",
    counts: [1425, 1332, 1147, 749, 350],
    classes: [
      { id: "Fornborg", counts: [848, 791, 650, 359, 139] },
      { id: "Fästning/skans", counts: [242, 227, 206, 158, 74] },
      { id: "Borg", counts: [226, 214, 195, 152, 88] },
      { id: "Slott/herresäte", counts: [56, 54, 51, 44, 30] },
      { id: "Stadsbefästning", counts: [18, 18, 18, 17, 13] },
      { id: "Stadsvall/stadsmur", counts: [14, 14, 14, 13, 5] },
      { id: "Stridsvärn", counts: [8, 4, 4, 3, 0] },
      { id: "Militär anläggning övrig", counts: [4, 3, 3, 1, 1] },
      { id: "Område med militära anläggningar", counts: [3, 2, 2, 1, 0] },
      { id: "Spärranordning", counts: [3, 3, 2, 1, 0] },
      { id: "Vallanläggning", counts: [3, 2, 2, 0, 0] },
    ],
  },
  {
    id: "religious",
    icon: "church",
    counts: [327, 301, 260, 195, 115],
    classes: [
      { id: "Kyrka/kapell", counts: [269, 249, 214, 160, 94] },
      { id: "Kloster", counts: [32, 32, 31, 28, 19] },
      { id: "Källa med tradition", counts: [13, 10, 7, 4, 1] },
      { id: "Naturföremål/-bildning med bruk, tradition eller namn", counts: [6, 4, 4, 1, 1] },
      { id: "Avrättningsplats", counts: [3, 3, 2, 1, 0] },
      { id: "Plats med tradition", counts: [2, 2, 1, 0, 0] },
      { id: "Samlingsplats", counts: [2, 1, 1, 1, 0] },
    ],
  },
  {
    id: "settlement",
    icon: "settlement",
    counts: [98, 81, 57, 37, 9],
    classes: [
      { id: "Boplats", counts: [28, 24, 16, 13, 2] },
      { id: "Hägnad", counts: [19, 13, 9, 6, 0] },
      { id: "Bytomt/gårdstomt", counts: [13, 12, 10, 5, 1] },
      { id: "Husgrund, förhistorisk/medeltida", counts: [12, 10, 6, 6, 3] },
      { id: "Stadslager", counts: [10, 8, 7, 2, 1] },
      { id: "Husgrund, historisk tid", counts: [4, 4, 4, 3, 2] },
      { id: "Boplatsområde", counts: [3, 3, 1, 0, 0] },
      { id: "Hägnadssystem", counts: [3, 3, 2, 1, 0] },
      { id: "Park-/trädgårdsanläggning", counts: [3, 2, 1, 1, 0] },
      { id: "Lägenhetsbebyggelse", counts: [2, 1, 0, 0, 0] },
      { id: "Gistgård", counts: [1, 1, 1, 0, 0] },
    ],
  },
  {
    id: "farming",
    icon: "fossil-field",
    counts: [17, 14, 9, 3, 1],
    classes: [
      { id: "Dike/ränna", counts: [4, 4, 2, 1, 0] },
      { id: "Fossil åker", counts: [4, 4, 2, 0, 0] },
      { id: "Område med fossil åkermark", counts: [4, 2, 2, 1, 1] },
      { id: "Terrassering", counts: [3, 2, 1, 1, 0] },
      { id: "Dammvall", counts: [2, 2, 2, 0, 0] },
    ],
  },
  {
    id: "industry",
    icon: "furnace",
    counts: [152, 118, 69, 24, 7],
    classes: [
      { id: "Hytt- och hammarområde", counts: [34, 28, 14, 7, 1] },
      { id: "Gruvområde", counts: [30, 23, 16, 9, 5] },
      { id: "Hyttområde", counts: [20, 16, 7, 2, 0] },
      { id: "Hammarområde", counts: [13, 10, 8, 4, 0] },
      { id: "Hyttlämning", counts: [13, 9, 4, 0, 0] },
      { id: "Hammare/smedja", counts: [7, 5, 2, 0, 0] },
      { id: "Metallindustri/järnbruk", counts: [7, 7, 6, 1, 0] },
      { id: "Pappersindustri", counts: [5, 3, 3, 1, 1] },
      { id: "Tegelindustri", counts: [5, 5, 3, 0, 0] },
      { id: "Småindustriområde", counts: [3, 2, 2, 0, 0] },
      { id: "Bergshistorisk lämning övrig", counts: [2, 0, 0, 0, 0] },
      { id: "Glasindustri", counts: [2, 2, 2, 0, 0] },
      { id: "Kalkugn", counts: [2, 0, 0, 0, 0] },
      { id: "Kvarn", counts: [2, 2, 0, 0, 0] },
      { id: "Livsmedelsindustri", counts: [2, 1, 1, 0, 0] },
      { id: "Uppfordringsanläggning", counts: [2, 2, 0, 0, 0] },
      { id: "Blästbrukslämning", counts: [1, 1, 0, 0, 0] },
      { id: "Område med flottningsanläggningar", counts: [1, 1, 0, 0, 0] },
      { id: "Träindustri", counts: [1, 1, 1, 0, 0] },
    ],
  },
  {
    id: "transport",
    icon: "bridge",
    counts: [66, 56, 34, 22, 7],
    classes: [
      { id: "Färdväg", counts: [26, 21, 12, 9, 3] },
      { id: "Bro", counts: [12, 9, 4, 2, 0] },
      { id: "Kanal", counts: [10, 9, 3, 1, 0] },
      { id: "Gränsbestämt område", counts: [9, 9, 8, 7, 3] },
      { id: "Vägmärke", counts: [4, 3, 3, 1, 1] },
      { id: "Gränsmärke", counts: [3, 3, 2, 1, 0] },
      { id: "Färdvägssystem", counts: [2, 2, 2, 1, 0] },
    ],
  },
  {
    id: "maritime",
    icon: "lighthouse",
    counts: [22, 16, 10, 5, 1],
    classes: [
      { id: "Fiskeläge", counts: [6, 4, 2, 0, 0] },
      { id: "Hamnområde", counts: [4, 2, 1, 1, 0] },
      { id: "Fyr", counts: [3, 3, 2, 1, 0] },
      { id: "Vårdkase", counts: [3, 2, 1, 0, 0] },
      { id: "Sjömärke", counts: [2, 1, 0, 0, 0] },
      { id: "Varv/slip", counts: [2, 2, 2, 1, 0] },
      { id: "Båtlänning", counts: [1, 1, 1, 1, 1] },
      { id: "Hamnanläggning", counts: [1, 1, 1, 1, 0] },
    ],
  },
  {
    id: "hunting",
    icon: "pitfall-trap",
    counts: [2, 2, 1, 0, 0],
    classes: [
      { id: "Fångstanläggning övrig", counts: [1, 1, 0, 0, 0] },
      { id: "Fångstgrop", counts: [1, 1, 1, 0, 0] },
    ],
  },
  {
    id: "misc",
    icon: "unknown",
    counts: [12, 12, 8, 0, 0],
    classes: [
      { id: "Fornlämningsliknande bildning", counts: [9, 9, 6, 0, 0] },
      { id: "Övrigt", counts: [2, 2, 2, 0, 0] },
      { id: "Fornlämningsliknande lämning", counts: [1, 1, 0, 0, 0] },
    ],
  },
];

export const ALL_FAMILY_IDS = FILTER_FAMILIES.map(f => f.id);
